name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
              QyNTUxOQAAACBoxd2WYcB8uq1UKShsxDnWCp9pWTN6IN5mbza+z8jjKAAAAJjnafE852nx
              PAAAAAtzc2gtZWQyNTUxOQAAACBoxd2WYcB8uq1UKShsxDnWCp9pWTN6IN5mbza+z8jjKA
              AAAECz72XIz/evdTpIA0cFFSiaAh2G5PTkm2SRhiM7h9RybmjF3ZZhwHy6rVQpKGzEOdYK
              n2lZM3og3mZvNr7PyOMoAAAAFWFybm9ieHRyZW1lQGdtYWlsLmNvbQ==
          -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 143.198.204.83 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@143.198.204.83 \
            'cd /root/10MS_Booking-management && git pull && pm2 reload all'
